trigger:
  branches:
    include:
      - main
      - dev

pool:
  vmImage: ubuntu-latest

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "18.18.x"
    displayName: "Install Node.js"

  - task: npmAuthenticate@0
    displayName: "NPM: Authenticate"
    inputs:
      workingFile: ".npmrc"

  - script: |
      npm install -g yarn
    displayName: "Install Yarn"

  - script: |
      yarn install
    displayName: "Install dependencies"

  - script: |
      yarn build
    displayName: "Build the project"

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: "$(Build.Repository.LocalPath)"
      includeRootFolder: false
      archiveType: "zip"
      archiveFile: "$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip"
      replaceExistingArchive: true
    displayName: "Archive files"

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: "$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip"
      artifactName: "drop"
      publishLocation: "Container"
    displayName: "Publish build artifacts"
